/** Hebrew interface strings: key = the English text used in the code, value = the Hebrew text. */
export const HE: Record<string, string> = {
  "(click for how-to)": "(לחצו להסבר)",
  "(nothing printed)": "(לא הודפס דבר)",
  "A tiny built-in engine draws the screen for you. Python and JavaScript games run live with your keyboard; C, C++ and C# games are compiled on a server, so the browser plays back the frames your program draws.": "מנוע קטן ומובנה מצייר עבורכם את המסך. משחקי Python ו-JavaScript רצים בזמן אמת עם המקלדת שלכם; משחקי C, C++ ו-C# מקומפלים בשרת, ולכן הדפדפן מנגן את הפריימים שהתוכנית שלכם מציירת.",
  "All done - pick another track": "סיימתם הכול - בחרו מסלול נוסף",
  "Back home": "חזרה לדף הבית",
  "Before you start: set up your computer": "לפני שמתחילים: הכינו את המחשב",
  "Best score so far:": "התוצאה הטובה ביותר עד כה:",
  "Build something real, one small step at a time. Every step has hints, and each one builds on the last.": "בנו משהו אמיתי, צעד קטן אחר צעד. בכל שלב יש רמזים, וכל שלב נשען על הקודם לו.",
  "Cancel": "ביטול",
  "Check answer": "בדיקת תשובה",
  "Check answers": "בדיקת תשובות",
  "Choose a track": "בחרו מסלול",
  "Choose the language of the website and of the lesson explanations. Code, file names and program output always stay in English. Lessons that are not translated yet are shown in English.": "בחרו את שפת האתר ואת שפת הסברי השיעורים. קוד, שמות קבצים ופלט של תוכניות תמיד נשארים באנגלית. שיעורים שעדיין לא תורגמו מוצגים באנגלית.",
  "Click the game to use the keyboard": "לחצו על המשחק כדי להשתמש במקלדת",
  "Close": "סגירה",
  "Compiled": "שפות מקומפלות",
  "Console": "Console",
  "Continue": "המשך",
  "Correct, nice work! 🎉": "נכון, כל הכבוד! 🎉",
  "Data": "נתונים",
  "Data, AI and APIs": "נתונים, בינה מלאכותית ו-API",
  "Delete all progress and saved code?": "למחוק את כל ההתקדמות והקוד השמור?",
  "Download": "הורדה",
  "Download project": "הורדת הפרויקט",
  "Download these files as a zip": "הורדת הקבצים כקובץ zip",
  "Download this project as a folder you can run, publish and show in a portfolio": "הורידו את הפרויקט כתיקייה שאפשר להריץ, לפרסם ולהציג בתיק העבודות",
  "Expected": "צפוי",
  "Extra header name (optional)": "שם header נוסף (לא חובה)",
  "Extra header value (optional)": "ערך header נוסף (לא חובה)",
  "Frame": "פריים",
  "Frozen - press Run to restart": "המשחק קפוא - לחצו על הרצה כדי להתחיל מחדש",
  "Game": "משחק",
  "Games": "משחקים",
  "Guided projects": "פרויקטים מודרכים",
  "HTML, CSS, JavaScript, TypeScript, React, Python and SQL run entirely inside your browser. Compiled languages need a real compiler, so their code is sent to a code-execution server. By default this uses the free public Judge0 server, which can be slow or rate-limited. For reliable use, run your own (see the README).": "HTML, CSS, JavaScript, TypeScript, React, Python ו-SQL רצים כולם בתוך הדפדפן שלכם. שפות מקומפלות דורשות מהדר אמיתי, ולכן הקוד שלהן נשלח לשרת להרצת קוד. כברירת מחדל נעשה שימוש בשרת Judge0 הציבורי והחינמי, שעלול להיות איטי או מוגבל בקצב הבקשות. לשימוש אמין, הריצו שרת משלכם (ראו את ה-README).",
  "Hide": "הסתרה",
  "Hide hints": "הסתרת הרמזים",
  "Hint": "רמז",
  "Hint {n} of {total}:": "רמז {n} מתוך {total}:",
  "Hint {n}:": "רמז {n}:",
  "How to:": "איך עושים זאת:",
  "Input": "קלט",
  "Inside Code Academy you do not have to install anything, every lesson runs in the page. When you want to run the same code on your own machine, this is what you need. Open a card for the full steps.": "ב-Code Academy אין צורך להתקין דבר, כל שיעור רץ ישירות בדף. כשתרצו להריץ את אותו קוד על המחשב שלכם, זה מה שצריך. פתחו כרטיס כדי לראות את כל השלבים.",
  "Inside Code Academy you do not have to install anything. These notes are for running the same code on your machine.": "ב-Code Academy אין צורך להתקין דבר. ההערות האלה מיועדות להרצת אותו קוד על המחשב שלכם.",
  "Install them all at once from a terminal:": "התקינו את כולם בבת אחת מהטרמינל:",
  "Language": "שפה",
  "Learn": "לימוד",
  "Learn to code by": "ללמוד תכנות דרך",
  "Lesson": "שיעור",
  "Lesson not found": "השיעור לא נמצא",
  "Lesson {n} of {total}": "שיעור {n} מתוך {total}",
  "Load into editor": "טעינה לעורך",
  "Loading...": "טוען...",
  "Machine learning with NumPy, pandas and scikit-learn, web APIs (REST and SOAP) against a practice server, and algorithms.": "למידת מכונה עם NumPy, pandas ו-scikit-learn, ממשקי API לרשת (REST ו-SOAP) מול שרת תרגול, ואלגוריתמים.",
  "Make games": "יצירת משחקים",
  "Mark lesson as complete": "סימון השיעור כהושלם",
  "My Judge0 (localhost:2358)": "Judge0 שלי (localhost:2358)",
  "My Piston (localhost:2000)": "Piston שלי (localhost:2000)",
  "Next hint ({n}/{total})": "הרמז הבא ({n}/{total})",
  "Next lesson →": "השיעור הבא ←",
  "Next →": "הבא ←",
  "No quiz for this lesson yet.": "עדיין אין חידון לשיעור הזה.",
  "Not quite yet.": "עוד לא בדיוק.",
  "Nothing printed yet.": "עדיין לא הודפס דבר.",
  "Open the sandbox": "פתחו את ארגז החול",
  "Output": "פלט",
  "Page not found": "הדף לא נמצא",
  "Pause": "השהיה",
  "Perfect!": "מושלם!",
  "Play": "הפעלה",
  "Player input": "קלט השחקן",
  "Playing - keyboard is captured": "המשחק פועל - המקלדת תפוסה",
  "Practice in the sandbox": "תרגלו בארגז החול",
  "Press Run (or Ctrl/Cmd + Enter) to see your output here.": "לחצו על הרצה (או Ctrl/Cmd + Enter) כדי לראות כאן את הפלט.",
  "Press Run to start your game. Then click it and use the keyboard.": "לחצו על הרצה כדי להתחיל את המשחק. אחר כך לחצו עליו והשתמשו במקלדת.",
  "Press Run. Your program draws every frame, then the browser plays it back here.": "לחצו על הרצה. התוכנית שלכם מציירת כל פריים, ואז הדפדפן מנגן אותו כאן.",
  "Preview": "תצוגה מקדימה",
  "Program input (one line per input() / scanf / cin / ReadLine call)": "קלט לתוכנית (שורה אחת לכל קריאה ל-input() / scanf / cin / ReadLine)",
  "Progress and your code are saved in this browser only.": "ההתקדמות והקוד שלכם נשמרים בדפדפן הזה בלבד.",
  "Public Judge0 (default)": "Judge0 ציבורי (ברירת מחדל)",
  "Quiz": "חידון",
  "Recommended VS Code extensions:": "תוספים מומלצים ל-VS Code:",
  "Replay from the start": "הפעלה חוזרת מההתחלה",
  "Requirements and how-to": "דרישות והוראות",
  "Reset": "איפוס",
  "Reset all progress...": "איפוס כל ההתקדמות...",
  "Reset to the starting code": "איפוס לקוד ההתחלתי",
  "Result": "תוצאה",
  "Reveal one hint at a time. Click again for a bigger hint.": "חושפים רמז אחד בכל פעם. לחצו שוב לקבלת רמז גדול יותר.",
  "Review the explanations above and try again.": "קראו שוב את ההסברים שלמעלה ונסו שוב.",
  "Run": "הרצה",
  "Run server for C, C++, C#, Java, Go and Rust": "שרת הרצה עבור C, C++, C#, Java, Go ו-Rust",
  "Run your program to record and play the game.": "הריצו את התוכנית כדי להקליט ולנגן את המשחק.",
  "Running...": "רץ...",
  "Sample data": "נתוני דוגמה",
  "Sandbox": "ארגז חול",
  "Scripting": "סקריפטים",
  "Server URL": "כתובת השרת",
  "Server type": "סוג השרת",
  "Settings": "הגדרות",
  "Setup": "הכנה",
  "Setup on your computer": "הכנה במחשב שלכם",
  "Short lessons, quick quizzes and a sandbox for every language. Nothing to install. Your progress stays in your browser.": "שיעורים קצרים, חידונים מהירים וארגז חול לכל שפה. אין צורך להתקין דבר. ההתקדמות שלכם נשארת בדפדפן.",
  "Solution": "פתרון",
  "Speed": "מהירות",
  "Start": "התחלה",
  "Start with HTML & CSS": "התחילו עם HTML ו-CSS",
  "Starting...": "מתחיל...",
  "Step {n} of {total}": "שלב {n} מתוך {total}",
  "Still stuck? Press \"Solution\" to see the full answer, then try to understand each line.": "עדיין תקועים? לחצו על \"פתרון\" כדי לראות את התשובה המלאה, ואז נסו להבין כל שורה.",
  "Stop": "עצירה",
  "Stopped": "המשחק נעצר",
  "Take the quiz": "גשו לחידון",
  "Test connection": "בדיקת חיבור",
  "Testing...": "בודק...",
  "That was the last step. Use \"Download project\" to get the whole thing as a folder with a README, ready for GitHub.": "זה היה השלב האחרון. לחצו על \"הורדת הפרויקט\" כדי לקבל את הכול כתיקייה עם README, מוכנה ל-GitHub.",
  "The game did not behave as expected yet.": "המשחק עדיין לא מתנהג כמצופה.",
  "The output is not what we expected yet.": "הפלט עדיין לא כמו שציפינו.",
  "The page should contain an element matching \"{selector}\".": "הדף צריך להכיל אלמנט שמתאים ל-\"{selector}\".",
  "The page should show the text \"{text}\".": "הדף צריך להציג את הטקסט \"{text}\".",
  "The player's key presses. One line per event: <frame> <key> <down|up>. Keys: left right up down space a d w s z x enter. Lines starting with # are notes.": "לחיצות המקשים של השחקן. שורה אחת לכל אירוע: <frame> <key> <down|up>. מקשים: left right up down space a d w s z x enter. שורות שמתחילות ב-# הן הערות.",
  "The preview did not finish loading. Try running again.": "התצוגה המקדימה לא סיימה להיטען. נסו להריץ שוב.",
  "This lesson is not translated to Hebrew yet, so it is shown in English.": "השיעור הזה עדיין לא תורגם לעברית, ולכן הוא מוצג באנגלית.",
  "Tools": "כלים",
  "Track not found": "המסלול לא נמצא",
  "Try again": "נסו שוב",
  "Try to understand every line before you copy it.": "נסו להבין כל שורה לפני שאתם מעתיקים אותה.",
  "Type the input your program should read...": "כתבו את הקלט שהתוכנית שלכם צריכה לקרוא...",
  "View the source code on GitHub": "צפייה בקוד המקור ב-GitHub",
  "View the source code on GitHub (opens in a new tab)": "צפייה בקוד המקור ב-GitHub (נפתח בלשונית חדשה)",
  "Web": "אינטרנט",
  "What you need on your own computer": "מה צריך במחשב שלכם",
  "Yes, delete": "כן, למחוק",
  "You got {score} of {total}.": "עניתם נכון על {score} מתוך {total}.",
  "You need:": "מה צריך:",
  "Your code has an error, so it could not finish. Read the red message in the output, fix it, then check again.": "יש שגיאה בקוד שלכם, ולכן הוא לא הצליח לסיים. קראו את ההודעה האדומה בפלט, תקנו, ואז בדקו שוב.",
  "Your code should contain something like: {pattern}": "הקוד שלכם צריך להכיל משהו כמו: {pattern}",
  "Your progress": "ההתקדמות שלכם",
  "Yours": "שלכם",
  "actually coding": "תכנות של ממש",
  "advanced": "מתקדם",
  "beginner": "מתחיל",
  "frame": "פריים",
  "intermediate": "בינוני",
  "lessons": "שיעורים",
  "not set": "לא מוגדר",
  "steps": "שלבים",
  "{selector} should have {property}: {value} (it is currently {current}).": "ל-{selector} צריך להיות {property}: {value} (כרגע: {current}).",
  "{selector} still has the default {property}. Change it.": "ל-{selector} עדיין יש את ברירת המחדל של {property}. שנו אותה.",
  "← All tracks": "→ כל המסלולים",
  "← Previous": "→ הקודם",
  "✓ Completed (click to undo)": "✓ הושלם (לחצו לביטול)",
};
