import type { Track } from '../lib/types';

/** Add a new track here, then drop its lessons in src/content/<track id>/NN-name.md */
export const TRACKS: Track[] = [
  { id: 'html-css', title: 'HTML & CSS', tagline: 'Build and style your first web pages.', color: '#f97316', icon: '</>', sandbox: 'web' },
  { id: 'css-frameworks', title: 'CSS Frameworks', tagline: 'Bootstrap and Tailwind: build good-looking pages fast with ready-made classes.', color: '#7c3aed', icon: 'CSS+', sandbox: 'web',
    intro: 'Frameworks give you ready-made styles so you do not write every rule yourself. You will learn Bootstrap (components and a grid you assemble from class names) and Tailwind (small utility classes you combine), then compare them so you can choose.\n\nIn the lessons you add the usual CDN link or script tag to your HTML, exactly as you would in a real project. The preview has the libraries built in, so it works offline.' },
  { id: 'javascript', title: 'JavaScript', tagline: 'Make pages come alive with real programming.', color: '#eab308', icon: 'JS', sandbox: 'js' },
  { id: 'typescript', title: 'TypeScript', tagline: 'JavaScript with types that catch bugs early.', color: '#3b82f6', icon: 'TS', sandbox: 'ts' },
  { id: 'react', title: 'React', tagline: 'Build interfaces from reusable components.', color: '#22d3ee', icon: '⚛', sandbox: 'react' },
  { id: 'python', title: 'Python', tagline: 'Friendly, readable code for almost anything.', color: '#22c55e', icon: 'Py', sandbox: 'python' },
  { id: 'sql', title: 'SQL', tagline: 'Ask questions of your data.', color: '#a855f7', icon: 'DB', sandbox: 'sql' },
  { id: 'c', title: 'C', tagline: 'Learn how computers really work.', color: '#64748b', icon: 'C', sandbox: 'c' },
  { id: 'cpp', title: 'C++', tagline: 'Fast, powerful, and everywhere.', color: '#0ea5e9', icon: 'C++', sandbox: 'cpp' },
  { id: 'csharp', title: 'C#', tagline: 'Modern, typed code for apps and games.', color: '#8b5cf6', icon: 'C#', sandbox: 'csharp' },
  { id: 'java', title: 'Java', tagline: 'Classes, objects and the language behind Android and big systems.', color: '#f59e0b', icon: 'Jv', sandbox: 'java' },
  { id: 'go', title: 'Go', tagline: 'Simple, fast code with goroutines for doing many things at once.', color: '#06b6d4', icon: 'Go', sandbox: 'go' },
  { id: 'rust', title: 'Rust', tagline: 'Fast code that the compiler keeps safe.', color: '#ea580c', icon: 'Rs', sandbox: 'rust' },
  { id: 'machine-learning', title: 'Machine Learning', tagline: 'From your first data table to training and judging real models.', color: '#ec4899', icon: 'ML', sandbox: 'ml', group: 'data',
    intro: 'Learn machine learning by doing it: load data with pandas, draw charts with matplotlib, train models with scikit-learn, then open the box and build gradient descent and a neural network yourself.\n\nThe libraries download the first time you use them (a few seconds, needs internet) and then stay cached by your browser. All data is built into the lessons, so results are the same every time.' },
  { id: 'apis', title: 'REST & SOAP APIs', tagline: 'Talk to web services: requests, status codes, auth, XML envelopes.', color: '#14b8a6', icon: 'API', sandbox: 'api', group: 'data',
    intro: 'Every lesson talks to a practice server at https://api.academy.test that lives inside the page. It works offline, always gives the same answers, and resets on every run, so you can create and delete freely.\n\nYou will use fetch with GET, POST, PUT, PATCH and DELETE, read headers and status codes, sign in with tokens, handle errors and retries, and finish with SOAP: XML envelopes, faults and WSDL.' },
  { id: 'algorithms', title: 'Algorithms & Data Structures', tagline: 'Think like a problem solver: searching, sorting, stacks, trees, graphs.', color: '#f43f5e', icon: 'O(n)', sandbox: 'python', group: 'data' },
  { id: 'git-github', title: 'Git & GitHub', tagline: 'Save history, undo mistakes, branch, merge and publish your code.', color: '#f05133', icon: 'Git', sandbox: 'git', group: 'learn',
    intro: 'Git remembers every version of your project, and GitHub puts it online so you can share it and work with others. You will practise in a Git terminal built into the page: it understands the real commands (init, add, commit, branch, merge, push) and runs them on a pretend repository, so you can break things safely.\n\nTo use Git for real you install it on your computer (see the setup guide) and run the same commands.' },
  { id: 'node-backend', title: 'Node.js & Backend', tagline: 'Build servers and APIs with Node.js and Express.', color: '#16a34a', icon: 'Node', sandbox: 'node-backend', group: 'learn',
    intro: 'Node.js runs JavaScript outside the browser, so you can build servers, tools and APIs. You will use modules, files, events and async code, then build web servers with Express: routes, middleware, REST CRUD, errors, authentication and project structure.\n\nThe lessons run in a practice Node inside the page: files live in memory, and a server started with app.listen(3000) can be called with fetch("http://localhost:3000/...") in the same program. Real Node works the same way, except that it uses your real disk and network (see the setup guide).' },
  { id: 'testing-debugging', title: 'Testing & Debugging', tagline: 'Find bugs fast and write tests that keep your code honest.', color: '#e11d48', icon: 'Test', sandbox: 'node-backend', group: 'learn',
    intro: 'Every programmer spends time hunting bugs. You will learn to read error messages and stack traces, debug with logs and careful thinking, handle errors with try/catch, and write automatic tests (describe / it / expect, mocks, async tests, test-driven development) so bugs cannot sneak back in. A Python lesson shows the same ideas with unittest.' },
  { id: 'project-todo-web', title: 'Project: Todo App', tagline: 'Build and style a working to-do list with HTML, CSS and JavaScript.', color: '#f97316', icon: '✅', sandbox: 'web', group: 'projects',
    intro: 'You will build a complete to-do app: add tasks, tick them off, delete them, filter them and save them. Every step adds one feature to the code from the step before, and the starter code is always provided.' },
  { id: 'project-react-directory', title: 'Project: People Directory', tagline: 'A React app that loads people from an API, with search and detail views.', color: '#22d3ee', icon: '👥', sandbox: 'react', group: 'projects',
    intro: 'Build a small React app on top of a web API: load data with fetch, show loading and error states, search, select a person and edit them. The practice server at https://api.academy.test is built into the page.' },
  { id: 'project-api-client', title: 'Project: API Client Library', tagline: 'Write a reusable JavaScript client with auth, errors, retries and paging.', color: '#14b8a6', icon: '🔌', sandbox: 'api', group: 'projects',
    intro: 'Real apps never scatter fetch calls everywhere. You will build a small client library: a request helper, typed errors, sign-in, automatic retries for flaky servers, pagination, and a SOAP helper.' },
  { id: 'project-expense-tracker', title: 'Project: Expense Tracker', tagline: 'A Python program that records, summarises and reports spending.', color: '#22c55e', icon: '💸', sandbox: 'python', group: 'projects',
    intro: 'Build a small finance tool in Python: model expenses, group and total them, handle bad input, report by month and category, and format a neat text report.' },
  { id: 'project-chatbot', title: 'Project: Chatbot', tagline: 'A rule-based Python chatbot that remembers things and picks replies.', color: '#a855f7', icon: '🤖', sandbox: 'python', group: 'projects',
    intro: 'Start with a bot that repeats you and finish with one that matches patterns, remembers your name, keeps a conversation history and scores how well it understood you. No libraries needed.' },
  { id: 'project-library-db', title: 'Project: Library Database', tagline: 'Design tables and answer real questions with SQL.', color: '#8b5cf6', icon: '📚', sandbox: 'sql', group: 'projects',
    intro: 'A library needs a database. You will create tables, add data, then write the queries a librarian needs: who has what, what is overdue, which books are most popular.' },
  { id: 'project-house-prices', title: 'Project: House Price Predictor', tagline: 'An end-to-end machine learning project, from raw data to a trained model.', color: '#ec4899', icon: '🏠', sandbox: 'ml', group: 'projects',
    intro: 'Explore a housing dataset, clean it, pick features, train and compare models, and judge them honestly with a held-out test set. This is how real machine learning projects go.' },
  { id: 'project-portfolio-site', title: 'Project: Portfolio Website', tagline: 'A real multi-page personal site you can publish on GitHub Pages.', color: '#7c3aed', icon: '🌐', sandbox: 'web', group: 'projects',
    intro: 'Build a personal portfolio with several pages (home, projects, about, contact), shared styling, Bootstrap or Tailwind, and good SEO and accessibility. At the end, download it as a folder and publish it for free. The links between your pages work in the preview.' },
  { id: 'project-react-blog', title: 'Project: Dev Blog (multi-file React)', tagline: 'A multi-page React app with components in folders and its own router.', color: '#22d3ee', icon: '📰', sandbox: 'react', group: 'projects',
    intro: 'Build a blog as a real multi-file React project: pages and components in folders, a small hash router you write yourself, posts loaded from the practice API, and a layout shared by every page. Download it at the end as a Vite project you can publish.' },
  { id: 'game-python', title: 'Python Games', tagline: 'Make real-time games with a tiny engine. Move, shoot, score.', color: '#16a34a', icon: '🎮', sandbox: 'pygame', group: 'games' },
  { id: 'game-c', title: 'C Games', tagline: 'Build a game loop in C and watch your frames play back.', color: '#64748b', icon: '👾', sandbox: 'cgame', group: 'games' },
  { id: 'game-cpp', title: 'C++ Games', tagline: 'Structs, classes and vectors, powering a small game.', color: '#0ea5e9', icon: '🚀', sandbox: 'cppgame', group: 'games' },
  { id: 'game-js', title: 'JavaScript Games', tagline: 'Make real-time canvas games with a tiny engine, right in the browser.', color: '#eab308', icon: '🎯', sandbox: 'jsgame', group: 'games' },
  { id: 'game-csharp', title: 'C# Games', tagline: 'Classes and lists drive a game, Unity-style.', color: '#8b5cf6', icon: '🕹️', sandbox: 'csgame', group: 'games' },
];
